server:
    port: 8080
spring:
    application:
        name: spring-boot-tutorial
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: Sathwik@3587
        url: jdbc:mysql://localhost:3306/springboot
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: "*"